name: Deploy Terraform

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    # 🔐 Décodage de la clé privée (toujours en base64 pour la sécurité)
    - name: Decode private key from Base64
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > atouzet.pem
        chmod 600 atouzet.pem

    # ✅ Ajout correct de la clé publique
    - name: Write SSH public key to file
      run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > atouzet.pub

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    # 🏗️ Terraform Apply directement (skip plan pour rapidité)
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
            -var="private_key_path=atouzet.pem" \
            -var="public_key_file=atouzet.pub" \
            -var="ami_id=${{ secrets.AMI_ID }}" \
            -var="key_name=${{ secrets.KEY_NAME }}" \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
